COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//drivers/utilities:onos-drivers-utilities',
    '//protocols/netconf/api:onos-protocols-restconf-api',
]

TEST_DEPS = [
    '//lib:TEST_ADAPTERS',
    '//core/api:onos-api-tests',
]

BUNDLES = [
    ':onos-drivers-restconf',
    '//drivers/utilities:onos-drivers-utilities',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
    test_deps = TEST_DEPS,
    resources_root = 'src/main/resources',
    resources = glob(['src/main/resources/**']),
)

onos_app (
    app_name = 'org.onosproject.drivers.restconf',
    title = 'RESTCONF Device Drivers',
    category = 'Drivers',
    url = 'http://onosproject.org',
    description = 'ONOS RESTCONF Device Drivers application.',
    included_bundles = BUNDLES,
    required_apps = [
        'org.onosproject.restconf'
    ],
)
